# Generated by Django 2.2.5 on 2021-12-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vivero', '0007_auto_20210518_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivero',
            name='departamento',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='vivero',
            name='municipio',
            field=models.CharField(max_length=60),
        ),
    ]
